name: Deploy to GitHub pages

on:
  push:
    branches: [ master, gh-actions ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install node modules
      run: npm install
    - name: Set up user
      run: |
        git config --global user.email "lyha@pdx.edu"
        git config --global user.name "Ha Ly"
    - name: Deploy to gh-pages
      env:
        REACT_APP_API_KEY: ${{ secrets.x_rapidapi_key }}
      run: npm run deploy
