name: Deploy to GitHub pages

on:
  push:
    branches: [ master, gh-actions ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install node modules
      run: npm install
    - name: Deploy to gh-pages
      env:
        REACT_APP_API_KEY: ${{ secrets.x_rapidapi_key }}
      run: npm run deploy
